export enum QueryOperator {
  EQUALS = 'EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  CONTAINS = 'CONTAINS',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  LESS_THAN = 'LESS_THAN',
  BIG_THAN = 'BIG_THAN',
  LESS_THAN_EQUALS = 'LESS_THAN_EQUALS',
  BIG_THAN_EQUALS = 'BIG_THAN_EQUALS',
  NULL = 'NULL',
  NOT_NULL = 'NOT_NULL',
}
